version: '3.8'

services:
  # Serviço da API (Backend Node.js)
  api:
    build: .
    ports:
      - "${API_EXTERNAL_PORT}:${PORT}"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      PORT: ${PORT}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_SECURE: ${COOKIE_SECURE}
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      # Lê as credenciais diretamente do .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Cria um volume para persistir os dados do banco
      - paad-data:/var/lib/postgresql/data
    # A porta do banco NÃO será exposta para a sua máquina,
    # apenas o serviço 'api' pode acessá-lo. (Mais seguro)
    restart: always

volumes:
  # Define o volume de dados
  paad-data: