version: '3.8'

services:
  # Serviço da API (Backend Node.js)
  api:
    build: .
    ports:
      # Mapeia a porta externa (da sua máquina) para a porta interna (do container)
      # Ex: "3500:3000"
      - "${API_EXTERNAL_PORT}:${PORT}"
    environment:
      # Monta a URL de conexão do Prisma usando as variáveis do .env
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      # Passa a porta interna para o container, para o server.js ler
      PORT: ${PORT}
    depends_on:
      - db
    restart: always

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      # Lê as credenciais diretamente do .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Cria um volume para persistir os dados do banco
      - paad-data:/var/lib/postgresql/data
    # A porta do banco NÃO será exposta para a sua máquina,
    # apenas o serviço 'api' pode acessá-lo. (Mais seguro)
    restart: always

volumes:
  # Define o volume de dados
  paad-data: